Homework
moonyalun/xsolla-docops-homework pull request #1
Opened 2020-08-25 05:32 UTC by moonyalun

2020-08-25 06:11 UTC, NickVolynkin requested changes

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +# <a name="введение"></a>1 Введение
Гитхаб должен сам делать якорные ссылки, необязательно их вручную добавлять.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +# <a name="введение"></a>1 Введение
И после единички нужна точка.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Реализовано два варианта взаимодействия с [Paystation API](https://secure.Xsolla.com/paystation2/api): в формате **post** или **get** запросов:
post и get — это методы протокола HTTP, они обычно пишутся заглавными: POST, GET.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +//Не хватает информации о строке токена, параметрах, как получить, использовать.
Это комментарии? Если хочется их оставить, можно оформить их блоком цитаты: `>`, потом пробел и текст.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +token |string |обязательный, но либо token либо json| Токен
Если `token` это текст, который обрабатывается машиной, то это код. Значит, его нужно оформить внутристрочным кодом.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +token |string |обязательный, но либо token либо json| Токен
Точно так же дальше в таблице с параметрами и типами.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +-   "user":{
Гитхаб тут верно подсвечивает минусы — их не может быть в формате JSON.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +-   "user":{
Обычно в JSON между ключом и значением ставят пробел, чтобы лучше читалось:
```json
"user": {
    "id": {}
}
```

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Общая схема взаимодействия ([рис. 1](#общая-схема-работы-с-paystation-api))  с [Paystation API](https://secure.Xsolla.com/paystation2/api) включает в себя 5 основных шагов:
двойной пробел перед "с"

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Общая схема взаимодействия ([рис. 1](#общая-схема-работы-с-paystation-api))  с [Paystation API](https://secure.Xsolla.com/paystation2/api) включает в себя 5 основных шагов:
Ссылка на картинку это здорово.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Построение интерфейса и обработка запросов описана в разделе [Обработка запросов](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.7xpc6mcqgzk4).
Тут предложения сливаются в один абзац, читателю может быть сложно вытащить из него отдельные ссылки. Я бы разбил на три абзаца или три элемента списка.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> + ![рис 1. Общая схема работы с Paystation API](1.png "Общая схема работы с Paystation API")
У картинки текст в квадратных скобках — это alt-text. Он виден, когда картинка не загрузилась или когда пользователь использует screen reader или другие специальные инструменты. Очень хорошо, что вы заполняете этот текст. https://moz.com/learn/seo/alt-text

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Инициализирующим запросом является запрос [Utils](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.ws7e5kigc9gf) из него можно получить всю необходимую и
Это очень длинная строка в исходнике, я бы разбил её на три-четыре. Так проще комментировать на ревью, так потом проще отслеживать изменения. Вот как-то так:
```md
Инициализирующим запросом является запрос
[Utils](https://docs.google.com/document/d/1gkqvf-0VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.ws7e5kigc9gf).
Из него можно получить всю необходимую информацию для работы сервиса.
В своём ответе он включает:
```

А ещё первое предложение лучше разбить, конечно.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +После получения корректного ответа от сервера в первую очередь нас интересует [Информацию о покупке](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.63r
нас интересует информация, не "информацию" :)

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +После получения корректного ответа от сервера в первую очередь нас интересует [Информацию о покупке](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.63r
И тоже лучше разбить на несколько строк и на два предложения.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +После получения корректного ответа от сервера в первую очередь нас интересует [Информацию о покупке](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.63r
Скобки и кавычки во внутристрочном фрагменте кода это сомнительно. 
```markdown
`("purchase")`
```
Стоит использовать, только если эти скобки и кавычки — часть программного кода. Тут у нас название параметра ответа, скобок в нём точно нет, кавычек на самом деле тоже. Кавычки появляются, когда мы этот параметр используем в JSON'е.

То есть оптимально так:
```markdown
 с помощью неё определяется передана ли покупка (`purchase`).
```

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Если да, то необходимо проверить наличие товара `("virtual_currency", "virtual_items", "subscription" или "subscription")` и наличие платёжной системы `("payment_system")`.
Тут то же самое что и в строке выше. Во внутристрочный код попало "или", там его не может быть.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Задача - построить магазин в котором пользователь сможет выбрать понравившийся ему товар и продолжить свою покупку.
здесь использован дефис-минус, а нужно длинное тире. 
https://unicode-table.com/ru/002D/
https://unicode-table.com/ru/2014/

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Здесь уже начинается построение интерфейса так как уже на этом этапе имеются все необходимые данные для построения **Header** и **Footer** окна магазина.
Header и footer это термины, но не названия, их пишут со строчной буквы. И если речь о сайте, то есть вполне прижившиеся русскоязычные термины, можно написать по-русски и продублировать.
```markdown
все данные для построения шапки (header) и подвала (footer) окна магазина.
```

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Здесь уже начинается построение интерфейса так как уже на этом этапе имеются все необходимые данные для построения **Header** и **Footer** окна магазина.
Ну и выделять термины полужирным не стоит, я считаю. Выделение привлекает внимание, так что эти слова читатель заметит раньше, чем весь абзац. Хотим ли мы этого в данном случае? Думаю, что нет.

Болд пригодился бы для подзаголовка в начале абзаца, например.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +В первую очередь используется информация из [инициализирующего запроса](#инициализирующий-запрос). Нас интересуют поля из объекта [настроек](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6V
оооооооооооооооооочень длинная строка. Можно разбить по точкам и каждую ссылку с новой строки начать.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +- чекбокс `спрашивать ли подтверждение в следующий раз`,
"спрашивать ли подтверждение в следующий раз" это не код, так что кавычки нужны.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +![открытие_магазина](3.png "Открытие магазина")
Альт-текст может и должен быть с пробелами. Это обычный человеческий текст.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +[Термины и определения](#термины-и-определения)
Оглавление — это очень хорошо. Но его лучше оформить многоуровневым списком, так будет компактнее и структура видна.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
>  # xsolla-docops-homework
Вот эту часть можно удалить.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +[Термины и определения](#термины-и-определения)
А перед оглавлением хорошо бы написать summary на 1-2 предложения. Для кого этот документ, что он поможет сделать? Так читателю не придётся скроллить вниз, чтобы это понять.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Это необходимо для определения дальнейших шагов, так, если в ответе содержится товар, то следует пропустить шаг № 2 ([рис. 1](#общая-схема-работы-с-paystation-api)), если же содержится платёжная сист
Тут немножко сложная для восприятия логика. И если я сразу открою шаг 2, но не прочитаю этот абзац, то не буду знать, что мне нужно его пропустить. Такое бывает очень часто, люди не читают документацию с начала до конца, как книгу.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Выбор покупки это второй шаг, если перед этим мы не получили товар `("virtual_currency", "virtual_items", "subscription" или "subscription")`.
Второй шаг находится под заголовком с номером 5.1.3, это прям очень сбивает с толку. Хорошо бы привести номера заголовков в соответствие с шагами.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +В первую очередь используется информация из [инициализирующего запроса](#инициализирующий-запрос). Нас интересуют поля из объекта [настроек](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6V
В обычном тексте мы обозначаем кавычками разные сущности, названия, в том числе сущности из программного кода. Так что в рукописном конспекте кавычки были бы идеальным выбором. Но здесь у нас есть специальный инструмент для обозначения внутристрочного кода. Поэтому кавычки избыточны, они обозначают то, что уже обозначено. Достаточно апострофов:
```
`goods_at_first`, `pricepoints_at_first`
```

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +В первую очередь используется информация из [инициализирующего запроса](#инициализирующий-запрос). Нас интересуют поля из объекта [настроек](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6V
И ещё между ссылкой и `("settings")` не хватает пробела, форматирование ломается.

2020-08-25 06:11 UTC, NickVolynkin commented on README.md
> +Инициализирующим запросом является запрос [Utils](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.ws7e5kigc9gf) из него можно получить всю необходимую и
И ещё в куче мест слишком длинные строки, стоит исправить везде.

2020-08-25 06:45 UTC, moonyalun commented on README.md
> +[Термины и определения](#термины-и-определения)
> Оглавление — это очень хорошо. Но его лучше оформить многоуровневым списком, так будет компактнее и структура видна.

пример синтаксиса не нашла

2020-08-25 06:54 UTC, NickVolynkin commented on README.md
> +[Термины и определения](#термины-и-определения)
А просто обычный список. 
```
* [4 Варианты взаимодействия с Paystation API](#варианты_взаимодействия)
    * [4.1 Серверная интеграция](#серверная-интеграция)
    * [4.2 Упрощенная интеграция](#упрощенная-интеграция)
* [5 Процесс работы сервиса](#процесс-работы-сервиса)
```

2020-08-29 06:27 UTC, NickVolynkin requested changes

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +Здесь приведено описание SDK – библиотеки, которая реализует функционирование магазина на основе Paystation API.
SDK (software development kit), как и библиотека — это имена нарицательные, не собственные. Так что полное название должно быть что-то вроде Xsolla Payments SDK.

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +Предназначена для упрощения использования платежного решения Xsolla разработчиками альтернативных платформ.
Альтернативных чему? Просто разных платформ )

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +      * [Шаг 1. Инициализирующий запрос](#шаг-1-инициализирующий-запрос)
Вот сейчас стала очень логичная структура заголовков. Номера шагов не конфликтуют с номерами заголовков.

Вообще, номера и не нужны нигде кроме пошаговых инструкций.

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +-   **sandbox** – специальный режим для безопасного исполнения и тестирования.
Хорошо, что не транслитерация ("сэндбокс"). Можно было бы продублировать русскоязычным термином "режим песочницы".

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +# 1. Цели создания
Цель создания — это термин из внутренней кухни, из общения между заказчиком документа и писателем. Для клиента — читателя этого документа — это скорее что-то вроде "Зачем вам Xsolla SDK".

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +## 3.2. Упрощённая интеграция
Кажется, тут заголовок слился с текстом перед ним, нужна отбивка пустой строкой

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +> Не хватает информации о строке токена, параметрах, как получить, использовать.
Если хотите добавить эту работу в свое портфолио, хорошо бы по этим комментариям доработать документ, а сами комментарии убрать. Это коммуникация между писателем и ревьюером, она не должна попадать в конечный документ

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +- Порядок запросов и переходов описан в разделе [Общая схема работы](https://docs.google.com/document/d/1gkqvf-70VZHFr3O0LbyK6VzTYDlng5b43ewYcwWszlA/edit#heading=h.amr87j4qq6ju).
Вот теперь список хорошо читается. 👍

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +их значения могут быть **0** или **1**.
0 и 1 это значения переменных, значит код, форматирование внутристрочным кодом

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +Далее пользователь выбирает какой либо из товаров и использует один их двух вариантов:
Какой-либо, один из

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +В случае покупки за реальную валюту сразу осуществляется переход к проверке пользовательского баланса, если баланса достаточно оплата продолжается через **Xsolla Balance**, в ином случае происходит о
Длинная строка и предложение длинное, лучше поразбивать

2020-08-29 06:27 UTC, NickVolynkin commented on README.md
> +При покупке за виртуальную валюту сперва выполняется запрос **Summary**, в котором находится содержимое нашей покупки и метка, которая говорит можно ли пропустить подтверждение от пользователя, если
Очень длинная строка

2020-08-29 08:20 UTC, moonyalun commented on README.md
> +      * [Шаг 1. Инициализирующий запрос](#шаг-1-инициализирующий-запрос)
Это была тренировка)

2020-08-29 08:23 UTC, moonyalun commented on README.md
> +-   **sandbox** – специальный режим для безопасного исполнения и тестирования.
поскольку префикс используется такой же, считаю оправдано использовать англ. вариант

2020-08-29 08:33 UTC, moonyalun commented on README.md
> +их значения могут быть **0** или **1**.
исправлено.

Как вообще закрывать замечания? правка + плюс ответ на соответсвующее замечание или как закрывать resolve conversations?

2020-08-29 09:00 UTC, moonyalun commented on README.md
> +При покупке за виртуальную валюту сперва выполняется запрос **Summary**, в котором находится содержимое нашей покупки и метка, которая говорит можно ли пропустить подтверждение от пользователя, если
отредактировано

2020-08-29 09:00 UTC, moonyalun commented on README.md
> +В случае покупки за реальную валюту сразу осуществляется переход к проверке пользовательского баланса, если баланса достаточно оплата продолжается через **Xsolla Balance**, в ином случае происходит о
отредактировано

2020-10-07 06:13 UTC, merged